package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// runDiagnose は diagnose の出力を取る(out に *os.File が要るので一時ファイル経由)。
func runDiagnose(t *testing.T, args ...string) string {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "out")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	if err := cmdDiagnose(args, f); err != nil {
		t.Fatalf("diagnose(%v): %v", args, err)
	}
	b, err := os.ReadFile(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func repo(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		p := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestDiagnoseIsReadOnly(t *testing.T) {
	dir := repo(t, map[string]string{"Dockerfile": "FROM alpine\nEXPOSE 8080\n"})
	before, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	runDiagnose(t, "--dir", dir)
	after, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(before) != len(after) {
		t.Fatalf("diagnose がファイルを作った: %d → %d", len(before), len(after))
	}
}

func TestDiagnoseRecommendation(t *testing.T) {
	multi := repo(t, map[string]string{
		"Dockerfile": "FROM alpine\nEXPOSE 8080\n",
		"compose.yaml": `services:
  gateway:
    build: .
  api:
    build: .
  worker:
    build: .
`,
	})
	out := runDiagnose(t, "--dir", multi)
	if !strings.Contains(out, "❯ apigateway") {
		t.Fatalf("複数サービスは API Gateway が既定のはず:\n%s", out)
	}
	if !strings.Contains(out, "no AWS calls were made") {
		t.Fatalf("読み取り専用であることの明示が無い:\n%s", out)
	}

	// 認証ありなら ALB か edge に寄り、API Gateway は使用不可として出る
	authed := runDiagnose(t, "--dir", multi, "--auth")
	if !strings.Contains(authed, "❯ edge") {
		t.Fatalf("認証あり(固定費 NG)は edge が既定のはず:\n%s", authed)
	}
	fixed := runDiagnose(t, "--dir", multi, "--auth", "--allow-fixed-cost")
	if !strings.Contains(fixed, "❯ alb") {
		t.Fatalf("認証あり(固定費 OK)は alb が既定のはず:\n%s", fixed)
	}
}

func TestDiagnoseShowsArchitectureAndFiles(t *testing.T) {
	// 入口の名前だけでは「AWS 上でどういう形になるか」「何が生えるか」が
	// 分からない。diagnose はその 2 つを出すのが仕事(#136)
	dir := repo(t, map[string]string{
		"go.mod":     "module x\nrequire github.com/go-sql-driver/mysql v1.10.0\n",
		"main.go":    "package main\nfunc main() {}\n",
		"Dockerfile": "FROM alpine\nEXPOSE 8080\n",
	})
	out := runDiagnose(t, "--dir", dir)

	for _, want := range []string{
		"architecture",
		"共有 ALB",               // 入口(独自ドメインで配るのが init の既定)
		"Lambda (Web Adapter)", // compute
		"DB (RDS / sashiki)",   // facts 連動: DB ドライバを検出したので付く
		"go-sql-driver/mysql",  // その根拠
		"generated by `kagerou init`",
		"kagerou.yaml",
		".github/workflows/kagerou-preview.yml",
		"template.yaml",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("%q が出ていない:\n%s", want, out)
		}
	}
	// 既存 Dockerfile は上書きされないことが読み取れる
	if !strings.Contains(out, "上書きしない") {
		t.Errorf("既存 Dockerfile の扱いが出ていない:\n%s", out)
	}
}

func TestDiagnoseApigatewayHasScaffold(t *testing.T) {
	// 複数サービスは apigateway が既定。雛形があるので但し書きは出さず、
	// 共有ベースまで含めて生成物を並べる
	multi := repo(t, map[string]string{
		"Dockerfile": "FROM alpine\nEXPOSE 8080\n",
		"compose.yaml": `services:
  a:
    build: .
  b:
    build: .
`,
	})
	out := runDiagnose(t, "--dir", multi)
	if !strings.Contains(out, "❯ apigateway") {
		t.Fatalf("前提が崩れている(apigateway が既定のはず):\n%s", out)
	}
	if strings.Contains(out, "雛形はまだ無い") {
		t.Fatalf("雛形はあるのに無いと言っている:\n%s", out)
	}
	for _, want := range []string{"deploy/apigw-base.yaml", "VPC Link"} {
		if !strings.Contains(out, want) {
			t.Errorf("%q が出ていない:\n%s", want, out)
		}
	}
}

func TestDiagnoseEdgeAuth(t *testing.T) {
	// 静的のみ + 認証必須。ALB は S3 を守れないので edge になり、
	// 共有ベースは Lambda@Edge つきのほうが出る
	spa := repo(t, map[string]string{"package.json": `{"dependencies":{"astro":"5"}}`})
	out := runDiagnose(t, "--dir", spa, "--auth")
	if !strings.Contains(out, "❯ edge") {
		t.Fatalf("前提が崩れている(edge が既定のはず):\n%s", out)
	}
	for _, want := range []string{"deploy/edge-base.yaml", "deploy/edge-auth/index.mjs"} {
		if !strings.Contains(out, want) {
			t.Errorf("%q が出ていない:\n%s", want, out)
		}
	}
	// 認証なしの共有ベースと二重に出さない(どちらを deploy するのか読めなくなる)
	if strings.Contains(out, "deploy/preview-base.yaml") {
		t.Errorf("認証ありで preview-base も並べている:\n%s", out)
	}
	// compute が無いので、コンテナ側の生成物は出ない
	for _, notWant := range []string{"template.yaml", "Dockerfile"} {
		if strings.Contains(out, notWant) {
			t.Errorf("compute が無いのに %q を予告している:\n%s", notWant, out)
		}
	}
}

func TestDiagnoseJSON(t *testing.T) {
	dir := repo(t, map[string]string{
		"go.mod":              "module x\n\nrequire github.com/gorilla/websocket v1.5.0\n",
		"cmd/gateway/main.go": "package main\nfunc main() {}\n",
		"Dockerfile":          "FROM alpine\nEXPOSE 8080\n",
	})
	var d diagnosis
	if err := json.Unmarshal([]byte(runDiagnose(t, "--dir", dir, "--json")), &d); err != nil {
		t.Fatal(err)
	}
	if !d.Facts.Realtime {
		t.Fatal("WebSocket を検出できていない")
	}
	if d.Recommend != "alb" {
		t.Fatalf("realtime は alb が既定のはず: %q", d.Recommend)
	}
	if len(d.Reasons) == 0 {
		t.Fatal("理由が空")
	}
	for _, r := range d.Reasons {
		if r.Reason == "" {
			t.Fatalf("%s に理由が無い", r.Entrypoint)
		}
	}

	// 構成図と生成ファイルは JSON でも返す(貼り直さずに使える形で)
	if len(d.Diagram) == 0 {
		t.Fatal("diagram が空")
	}
	if d.Diagram[0] != "Browser" {
		t.Fatalf("図はブラウザから始まるはず: %q", d.Diagram[0])
	}
	if !strings.Contains(strings.Join(d.Diagram, "\n"), "ECS Fargate") {
		t.Fatalf("alb の図に compute が無い:\n%s", strings.Join(d.Diagram, "\n"))
	}
	if len(d.Files) == 0 {
		t.Fatal("files が空")
	}
	var paths []string
	for _, f := range d.Files {
		if f.Path == "" || f.Note == "" {
			t.Fatalf("files の要素が欠けている: %+v", f)
		}
		paths = append(paths, f.Path)
	}
	for _, want := range []string{"kagerou.yaml", "template.yaml", "deploy/alb-base.yaml"} {
		if !slices.Contains(paths, want) {
			t.Errorf("%q が files に無い: %v", want, paths)
		}
	}
}
