package main

// kagerou upgrade --check — 生成物が今の kagerou と何が違うかを出す(#207)。
//
// #212 の印は「古い」ことまでしか言えない。何が変わるのかは**生成し直して
// 比べる**しかなく、そのために生成入力を kagerou.yaml に残してある。
//
// 書き換えはしない。`--check` だけなのは、template.yaml のように
// **利用者が手を入れる前提**のファイルがあるからで、3-way マージを誤ると
// 本人の変更を消す。まず見えるようにして、実際にどこが手で変わるかを見てから
// 書き換えを足すかどうか決める。

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/rikukadev/kagerou/internal/genstamp"
	"github.com/rikukadev/kagerou/internal/scaffold"
)

func cmdUpgrade(args []string, out *os.File) error {
	fs := flag.NewFlagSet("upgrade", flag.ContinueOnError)
	dir := fs.String("dir", ".", "repository to inspect")
	check := fs.Bool("check", false, "report differences and exit non-zero if any (required; upgrade does not write)")
	full := fs.Bool("full", false, "also show the diff of files you are meant to edit (template.yaml etc.)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if !*check {
		return fmt.Errorf("kagerou upgrade only supports --check today " +
			"(rewriting files you may have edited needs a 3-way merge; see #207)")
	}

	cfgPath := filepath.Join(*dir, "kagerou.yaml")
	body, err := os.ReadFile(cfgPath)
	if err != nil {
		return fmt.Errorf("%s: %w (run this where kagerou init was run)", cfgPath, err)
	}

	p, ok := scaffold.ParseGenRecord(body)
	if !ok {
		// v0.13 以前の生成物。入力が分からないので、**推測で diff を出さない**。
		// 当てずっぽうの差分は「直すべき点」と見分けが付かず、害のほうが大きい
		stamp, hasStamp := genstamp.Parse(body)
		say(out, "no generation record in %s\n", cfgPath)
		if hasStamp {
			say(out, "  generated by kagerou %s, before the record was added\n", stamp)
		}
		say(out, "\n`kagerou validate` still reports known problems fixed since then.\n")
		say(out, "to get a diff, re-generate once with `kagerou init --force`\n")
		say(out, "(it overwrites; put your edits aside first) — after that this command works.\n")
		return nil
	}

	want, err := scaffold.Generate(p, scaffold.AllTargets())
	if err != nil {
		return err
	}

	var changed, missing, userChanged []string
	for _, f := range want {
		path := filepath.Join(*dir, f.Path)
		have, err := os.ReadFile(path)
		if err != nil {
			missing = append(missing, f.Path)
			continue
		}
		// 記録された入力で作り直して一致するなら、kagerou 側は何も変えていない
		if bytes.Equal(normalize(have), normalize(f.Body)) {
			continue
		}
		if f.Owner == scaffold.OwnerUser {
			userChanged = append(userChanged, f.Path)
			continue
		}
		changed = append(changed, f.Path)
	}

	if len(changed) == 0 && len(missing) == 0 {
		say(out, "up to date: kagerou-owned files match what %s generates\n", versionLabel())
		if len(userChanged) > 0 {
			// 差分があること自体は正常。件数だけ伝えて、中身は出さない
			say(out, "(%d file(s) you maintain differ, as expected: %s)\n",
				len(userChanged), strings.Join(userChanged, ", "))
			if *full {
				say(out, "\nrun with --full to see them\n")
			}
		}
		return nil
	}

	say(out, "these files are generated by kagerou and no longer match %s:\n", versionLabel())
	for _, f := range changed {
		say(out, "  changed  %s\n", f)
	}
	for _, f := range missing {
		say(out, "  missing  %s\n", f)
	}
	if len(userChanged) > 0 {
		say(out, "\nalso differing, but these are yours to edit (not a problem):\n")
		for _, f := range userChanged {
			say(out, "  %s\n", f)
		}
	}
	say(out, "\n`kagerou init --force` re-generates them. It overwrites, so put your edits aside first.\n")
	say(out, "`kagerou validate` names the known problems this fixes.\n")
	return fmt.Errorf("%d generated file(s) are out of date", len(changed)+len(missing))
}

func say(w io.Writer, format string, a ...any) { _, _ = fmt.Fprintf(w, format, a...) }

// versionLabel は開発ビルドで "dev" と出さないための表示名。
func versionLabel() string {
	if version == "" || version == "dev" {
		return "this build"
	}
	return "kagerou " + version
}

// normalize は比較の前に「意味の無い差」を落とす。
//
// 生成物には毎回変わりうるもの(バージョンの印、生成入力の記録)が入っている。
// そこだけで差分が出ると、**中身が同じでも毎回 changed になる**ので落とす。
// 行末の空白と末尾の改行も同じ理由で揃える。
func normalize(b []byte) []byte {
	var keep [][]byte
	for _, line := range bytes.Split(b, []byte("\n")) {
		s := bytes.TrimRight(line, " \t")
		if bytes.Contains(s, []byte(genstamp.Marker)) || bytes.Contains(s, []byte("kagerou:generated ")) {
			continue
		}
		keep = append(keep, s)
	}
	return bytes.TrimRight(bytes.Join(keep, []byte("\n")), "\n")
}
