package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rikukadev/kagerou/internal/scaffold"
)

// scaffoldInto は init と同じ経路で生成する。
func scaffoldInto(t *testing.T, dir string) scaffold.Params {
	t.Helper()
	for name, body := range map[string]string{
		"Dockerfile":   "FROM node:22\nEXPOSE 3000\n",
		"package.json": `{"dependencies":{"next":"15"}}`,
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	det := scaffold.Detect(dir)
	p := scaffold.Params{
		Project: "web", Region: "ap-northeast-1",
		Port: det.AppPort, HasDockerfile: det.HasDockerfile, Framework: det.Framework,
		DockerfileName: det.DockerfileName, HealthPath: det.HealthPath,
		Domain: "web.example.com", Entrypoint: "alb", Compute: "lambda",
	}
	if _, err := scaffold.Run(dir, p, scaffold.AllTargets(), false); err != nil {
		t.Fatal(err)
	}
	return p
}

func upgradeCheck(t *testing.T, dir string) (string, error) {
	t.Helper()
	out, err := os.CreateTemp(t.TempDir(), "out")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = out.Close() })
	cerr := cmdUpgrade([]string{"--check", "--dir", dir}, out)
	b, rerr := os.ReadFile(out.Name())
	if rerr != nil {
		t.Fatal(rerr)
	}
	return string(b), cerr
}

// 生成した直後は差分ゼロ。ここが落ちると、以降の判定が全部信用できない。
func TestUpgradeCheckCleanAfterInit(t *testing.T) {
	dir := t.TempDir()
	scaffoldInto(t, dir)
	s, err := upgradeCheck(t, dir)
	if err != nil {
		t.Fatalf("生成直後に差分が出ている: %v\n%s", err, s)
	}
	if !strings.Contains(s, "up to date") {
		t.Errorf("出力: %s", s)
	}
}

// #207 の動機そのもの: kagerou 側が直した内容が、生成済みの workflow に
// 届いていないことを検出する(#187 のリスナー優先度が実例)。
func TestUpgradeCheckFindsStaleGeneratedFile(t *testing.T) {
	dir := t.TempDir()
	scaffoldInto(t, dir)
	wf := filepath.Join(dir, ".github", "workflows", "kagerou-preview.yml")
	b, err := os.ReadFile(wf)
	if err != nil {
		t.Fatal(err)
	}
	old := strings.Replace(string(b), "configure-aws-credentials@v5", "configure-aws-credentials@v4", 1)
	if old == string(b) {
		t.Skip("workflow の中身が変わったのでこのテストの前提が古い")
	}
	if err := os.WriteFile(wf, []byte(old), 0o644); err != nil {
		t.Fatal(err)
	}
	s, err := upgradeCheck(t, dir)
	if err == nil {
		t.Fatalf("古い生成物を見逃した:\n%s", s)
	}
	if !strings.Contains(s, "kagerou-preview.yml") {
		t.Errorf("どのファイルか言っていない: %s", s)
	}
}

// 利用者が手を入れる前提のファイルでは鳴らない。
// ここで鳴ると毎回鳴ることになり、誰も読まなくなる。
func TestUpgradeCheckQuietOnUserOwnedEdits(t *testing.T) {
	dir := t.TempDir()
	scaffoldInto(t, dir)
	tp := filepath.Join(dir, "template.yaml")
	b, err := os.ReadFile(tp)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(tp, append(b, []byte("\n  # 私が足した\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	s, err := upgradeCheck(t, dir)
	if err != nil {
		t.Fatalf("利用者の編集で落ちている: %v\n%s", err, s)
	}
	if !strings.Contains(s, "template.yaml") {
		t.Errorf("触れてすらいない(件数は伝えるべき): %s", s)
	}
}

// 記録の無い生成物(v0.13 以前)では、推測の diff を出さずに次の手を示す。
func TestUpgradeCheckWithoutRecord(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "kagerou.yaml"),
		[]byte("# generated by kagerou v0.11.0\nproject: old\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	s, err := upgradeCheck(t, dir)
	if err != nil {
		t.Fatalf("記録が無いだけで落ちている: %v", err)
	}
	for _, want := range []string{"no generation record", "v0.11.0", "init --force"} {
		if !strings.Contains(s, want) {
			t.Errorf("出力に %q が無い: %s", want, s)
		}
	}
}

// --check 以外は受け付けない(書き換えは 3-way マージが要る)。
func TestUpgradeRefusesToWrite(t *testing.T) {
	out, err := os.CreateTemp(t.TempDir(), "out")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = out.Close() })
	if err := cmdUpgrade([]string{"--dir", t.TempDir()}, out); err == nil {
		t.Fatal("--check 無しは拒否されるべき")
	}
}
