package validate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeGen(t *testing.T, dir, name, body string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestGeneratedStamps(t *testing.T) {
	dir := t.TempDir()
	old := writeGen(t, dir, "kagerou.yaml", "# generated by kagerou v0.11.0\nproject: todo\n")
	cur := writeGen(t, dir, "template.yaml", "# generated by kagerou v0.13.0\nResources: {}\n")
	none := writeGen(t, dir, "deploy/alb-base.yaml", "Resources: {}\n")

	got := GeneratedStamps([]string{old, cur, none, filepath.Join(dir, "missing.yaml")}, "v0.13.0")
	all := ""
	for _, f := range got {
		if f.Level != Warn {
			t.Errorf("生成物の古さで error にしてはいけない(手を入れている可能性がある): %+v", f)
		}
		all += f.Msg + "\n"
	}

	if !strings.Contains(all, "kagerou.yaml") || !strings.Contains(all, "v0.11.0") {
		t.Errorf("古いファイルを名指ししていない:\n%s", all)
	}
	// パスで見る。Fix.Files の文面にも "template.yaml" が出るので部分一致では判定できない
	if strings.Contains(all, cur+":") {
		t.Errorf("最新のファイルを古いと言っている:\n%s", all)
	}
	if strings.Contains(all, "missing.yaml") {
		t.Errorf("存在しないファイルに触れている:\n%s", all)
	}
	if !strings.Contains(all, "alb-base.yaml") || !strings.Contains(all, "no kagerou version stamp") {
		t.Errorf("印の無いファイルを報告していない:\n%s", all)
	}
	// 「古い」だけでは動けない。踏む問題と次の行動が要る
	if !strings.Contains(all, "CREATE_FAILED") {
		t.Errorf("v0.11.0 の生成物が踏む既知の問題を名指ししていない:\n%s", all)
	}
	if !strings.Contains(all, "kagerou init --force") {
		t.Errorf("再生成のしかたを出していない:\n%s", all)
	}
}

// 開発ビルド(dev)では古さを判定しない。毎回警告が出ると誰も読まなくなる。
func TestGeneratedStampsQuietOnDevBuild(t *testing.T) {
	dir := t.TempDir()
	p := writeGen(t, dir, "kagerou.yaml", "# generated by kagerou v0.11.0\n")
	for _, f := range GeneratedStamps([]string{p}, "dev") {
		if strings.Contains(f.Msg, "v0.11.0") {
			t.Errorf("dev ビルドで古さを判定している: %+v", f)
		}
	}
}

// packaged.yaml はビルド成果物なので検査対象にしない(印が無くて当然)。
func TestGeneratedPathsForSkipsPackaged(t *testing.T) {
	for _, p := range GeneratedPathsFor("packaged-ssr.yaml") {
		if strings.Contains(p, "packaged") {
			t.Errorf("ビルド成果物が対象に入っている: %s", p)
		}
	}
	got := GeneratedPathsFor("e2e/aws/ssr/template.yaml")
	found := false
	for _, p := range got {
		if p == "e2e/aws/ssr/template.yaml" {
			found = true
		}
	}
	if !found {
		t.Errorf("設定が指すテンプレートが対象に入っていない: %v", got)
	}
}
