package validate

import (
	"fmt"
	"os"
	"strings"

	"github.com/rikukadev/kagerou/internal/genstamp"
)

// GeneratedFiles は init が書く生成物のうち、版を見る対象。
// template は設定で場所が変わるので、呼び出し側が足す。
var GeneratedFiles = []string{
	"kagerou.yaml",
	".github/workflows/preview.yml",
	".github/workflows/reap.yml",
	"deploy/preview-base.yaml",
	"deploy/alb-base.yaml",
	"deploy/apigw-base.yaml",
	"deploy/edge-base.yaml",
}

// GeneratedStamps は生成物のバージョン印を検査する(#207)。
//
// init が書いたファイルは利用者のものになるので、生成器のバグを直しても
// 既存のリポジトリには届かない。**黙って古いまま動いている**のが一番まずいので、
// 少なくとも「古い」ことと「それ以降に何を直したか」は言う。
//
// 直せないもの(利用者が手を入れたファイルかもしれない)を error にはしない。
func GeneratedStamps(paths []string, current string) []Finding {
	var out []Finding
	oldest := ""
	var unstamped []string
	var stale []genstamp.Fix

	for _, p := range paths {
		b, err := os.ReadFile(p)
		if err != nil {
			continue // 生成していない構成なら単に無い
		}
		v, ok := genstamp.Parse(b)
		if !ok {
			// 印が無い = 印を入れる前の kagerou で生成したか、手で書いたか。
			// どちらか分からないので断定せず、1 行にまとめて出す。
			unstamped = append(unstamped, p)
			continue
		}
		if !genstamp.Outdated(v, current) {
			continue
		}
		out = append(out, Finding{Warn, fmt.Sprintf(
			"%s: generated by kagerou %s (running %s)", p, v, current)})
		if oldest == "" || genstamp.Outdated(v, oldest) {
			oldest = v
		}
	}

	if len(unstamped) > 0 {
		out = append(out, Finding{Warn, fmt.Sprintf(
			"no kagerou version stamp (generated before stamping, or hand-written): %s",
			strings.Join(unstamped, ", "))})
	}
	if oldest != "" {
		stale = genstamp.StaleFixes(oldest)
	}
	for _, f := range stale {
		out = append(out, Finding{Warn, fmt.Sprintf(
			"fixed in %s but not in your files: %s (%s)", f.Version, f.Summary, f.Files)})
	}
	if len(stale) > 0 {
		out = append(out, Finding{Warn,
			"re-generate with `kagerou init --force` (it overwrites; keep your edits aside first)"})
	}
	return out
}

// GeneratedPathsFor は検査対象に、設定が指すテンプレートを足す。
func GeneratedPathsFor(template string) []string {
	paths := append([]string{}, GeneratedFiles...)
	if template != "" && !strings.HasPrefix(template, "packaged") {
		paths = append(paths, template)
	}
	return paths
}
