package genstamp

import "testing"

func TestParse(t *testing.T) {
	for _, tc := range []struct {
		name string
		body string
		want string
		ok   bool
	}{
		{"YAML のコメント", "# generated by kagerou v0.13.0 — 再生成は…\nproject: todo\n", "v0.13.0", true},
		{"JS のコメント", "// generated by kagerou v0.13.0\nexport const x = 1\n", "v0.13.0", true},
		{"shebang の後", "#!/bin/sh\n# generated by kagerou v1.2.3\n", "v1.2.3", true},
		{"印が無い", "project: todo\n", "", false},
		{"版が無い", "# generated by kagerou\n", "", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := Parse([]byte(tc.body))
			if ok != tc.ok || got != tc.want {
				t.Errorf("Parse = (%q, %v), want (%q, %v)", got, ok, tc.want, tc.ok)
			}
		})
	}
}

// 書いた印を自分で読めること。フォーマットを変えたときに両方直し忘れない。
func TestLineRoundTrip(t *testing.T) {
	for _, prefix := range []string{"#", "//"} {
		got, ok := Parse([]byte(Line(prefix, "v0.13.0")))
		if !ok || got != "v0.13.0" {
			t.Errorf("prefix %q: Parse = (%q, %v)", prefix, got, ok)
		}
	}
	// 次の行動が分かること(印だけあっても意味が無い)
	if l := Line("#", "v0.13.0"); !contains(l, "kagerou init") {
		t.Errorf("再生成のしかたが書かれていない: %q", l)
	}
}

func TestOutdated(t *testing.T) {
	for _, tc := range []struct {
		stamp, current string
		want           bool
	}{
		{"v0.12.0", "v0.13.0", true},
		{"0.12.0", "0.13.0", true},
		{"v0.12.0+abc123", "v0.13.0", true},
		{"v0.13.0", "v0.13.0", false},
		{"v0.14.0", "v0.13.0", false},
		{"v1.0.0", "v0.13.0", false},
		// 開発ビルドでは判定しない(毎回警告が出ると誰も読まなくなる)
		{"v0.12.0", "dev", false},
		{"dev", "v0.13.0", false},
	} {
		if got := Outdated(tc.stamp, tc.current); got != tc.want {
			t.Errorf("Outdated(%q, %q) = %v, want %v", tc.stamp, tc.current, got, tc.want)
		}
	}
}

// 「古い」だけでは何をすればいいか分からない。踏む問題を名指しできること。
func TestStaleFixes(t *testing.T) {
	if got := StaleFixes("v0.11.0"); len(got) == 0 {
		t.Error("v0.11.0 の生成物に既知の問題が出ていない")
	}
	if got := StaleFixes("v99.0.0"); len(got) != 0 {
		t.Errorf("新しい生成物に問題が出ている: %v", got)
	}
	// 印が読めないときは断定しない
	if got := StaleFixes("dev"); got != nil {
		t.Errorf("判定できないのに問題を出している: %v", got)
	}
	for _, f := range Fixes {
		if f.Version == "" || f.Files == "" || f.Summary == "" {
			t.Errorf("Fix の要素が欠けている: %+v", f)
		}
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}
