// Package genstamp は生成物に埋めるバージョン印と、その読み取りを扱う(#207)。
//
// kagerou init が書いたファイルは、書いた時点で**利用者のファイル**になる。
// こちらでバグを直しても既存ユーザーには届かないので、少なくとも
// 「そのファイルがいつの kagerou で作られたか」と「それ以降に何を直したか」は
// 言えるようにしておく。
//
// AWS も設定も触らない純粋なパッケージ。
package genstamp

import (
	"regexp"
	"strconv"
	"strings"
)

// Marker は印の本文。コメント記号の後ろに置く。
const Marker = "generated by kagerou"

// stampRe は印からバージョンを拾う。コメント記号は言語ごとに違うので見ない。
var stampRe = regexp.MustCompile(`generated by kagerou (v?\d+\.\d+\.\d+)`)

// Line はファイル先頭に埋める 1 行を返す。prefix はコメント記号("#" / "//")。
//
// 再生成のしかたを同じ行に書くのは、印だけあっても次の行動が分からないため。
func Line(prefix, version string) string {
	return prefix + " " + Marker + " " + version +
		" — 再生成は `kagerou init --force`(手を入れたファイルも上書きされる)"
}

// Parse は本文から印のバージョンを拾う。印が無ければ ok=false。
func Parse(body []byte) (version string, ok bool) {
	m := stampRe.FindSubmatch(body)
	if m == nil {
		return "", false
	}
	return string(m[1]), true
}

// Fix は「生成物の中身を直した」変更 1 件。生成済みのファイルには届かないので、
// validate が「あなたのファイルはこれを踏む」と言えるようにここに残す。
//
// **生成物の挙動が変わる修正だけ**を足すこと(文言の調整や整形は対象外)。
type Fix struct {
	Version string // 直った版(例 "v0.12.0")
	Files   string // 影響する生成物
	Summary string // 何が起きるか(現象を先に書く)
}

// Fixes は新しい順。生成物に影響した修正だけを載せる。
var Fixes = []Fix{
	{
		// Version はこの修正が **実際に入ったリリース**。PR を書いた時点の
		// 次リリース見込みを書くと、間のリリースで init した人(まさに
		// このバグを持つ人)に警告が出ない
		Version: "v0.15.0",
		Files:   "kagerou-setup.sh(preview base / alb base / apigw base の deploy)",
		Summary: "ベーススタックに kagerou タグが付かず、`kagerou cost` が基盤の固定費を 0 円として出す",
	},
	{
		Version: "v0.12.0",
		Files:   ".github/workflows/preview.yml, template.yaml(入口 = alb)",
		Summary: "5000 番台以降の PR でリスナールールの優先度が衝突し、環境の作成が CREATE_FAILED になる",
	},
	{
		Version: "v0.12.0",
		Files:   "deploy/apigw-base.yaml(入口 = apigateway・compute = ecs)",
		Summary: "Cloud Map が A レコードだと deploy は成功するのにリクエストが 503 になる(SRV が要る)",
	},
}

// StaleFixes は stamp より後に入った修正を返す(新しい順)。
// 印が読めないときは nil(何が入っているか分からないので、断定しない)。
func StaleFixes(stamp string) []Fix {
	s, ok := parseSemver(stamp)
	if !ok {
		return nil
	}
	var out []Fix
	for _, f := range Fixes {
		if v, ok := parseSemver(f.Version); ok && less(s, v) {
			out = append(out, f)
		}
	}
	return out
}

// Outdated は stamp が current より古いか。判定できなければ false。
func Outdated(stamp, current string) bool {
	s, ok1 := parseSemver(stamp)
	c, ok2 := parseSemver(current)
	if !ok1 || !ok2 {
		return false
	}
	return less(s, c)
}

// parseSemver は "v0.12.0" / "0.12.0+abc123" を [3]int にする。
// 開発ビルド("dev" や ldflags 未設定)は判定対象外。
func parseSemver(v string) ([3]int, bool) {
	v = strings.TrimPrefix(strings.TrimSpace(v), "v")
	if i := strings.IndexAny(v, "+-"); i >= 0 {
		v = v[:i]
	}
	parts := strings.Split(v, ".")
	if len(parts) != 3 {
		return [3]int{}, false
	}
	var out [3]int
	for i, p := range parts {
		n, err := strconv.Atoi(p)
		if err != nil {
			return [3]int{}, false
		}
		out[i] = n
	}
	return out, true
}

func less(a, b [3]int) bool {
	for i := range a {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return false
}
