package scaffold

// 生成に使った入力を kagerou.yaml に残す(#207)。
//
// バージョンの印(#212)だけでは「古い」ことしか分からない。**何が変わるのか**を
// 出すには生成し直して比べるしかなく、そのためには生成に使った入力が要る。
// 入力は kagerou.yaml から完全には復元できない(compute / entrypoint / 検出値は
// 設定に出ない)ので、生成時に書き残す。
//
// 置き場所は `.kagerou/generated.json`(#224)。当初は kagerou.yaml のコメントに
// 置いていたが、**機械が読むコメントは、宣言していないだけで既に契約**であり、
// 置き場所として脆かった:
//
//   - yamlfmt / yq / Prettier のような YAML を書き直す道具は**コメントを黙って落とす**。
//     CI に整形を入れているリポジトリでは、入った瞬間に記録が消える
//   - 消えても気づけない。upgrade --check は「記録の無い古いリポジトリ」と区別できず、
//     静かに機能を失う
//   - 利用者が kagerou.yaml を編集するとき、読まれていることを知らずに消し得る
//
// 独立したファイルなら、名前で所有者が読め、整形器の対象にもならない。
// 設定のキーとして足さないのは変わらない — CONTRACT の kagerou.yaml スキーマは
// 外部が依存してよい契約なので、そこを広げずに済ませる。
//
// 既に刻んだリポジトリを見捨てないため、**読み取りだけ**コメントも見る。

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
)

// genRecordPrefix は旧形式(kagerou.yaml のコメント)の目印。読み取りのみで使う。
const genRecordPrefix = "# kagerou:generated "

// GenRecordPath は生成入力の置き場所。整形器が触らない場所に置く(#224)。
const GenRecordPath = ".kagerou/generated.json"

// genRecordNote はファイルを開いた人向けの 1 行。JSON にコメントが書けないので
// フィールドとして持つ。
const genRecordNote = "generated by kagerou init — do not edit. read by `kagerou upgrade --check`."

// genRecordDoc は .kagerou/generated.json の中身。
type genRecordDoc struct {
	Note   string `json:"note"`
	Params Params `json:"params"`
}

// GenRecord は生成入力を JSON にする。テンプレートから呼ぶ。
//
// 検出値(Framework / Port / HealthPath …)も含める。再生成したときに
// **そのときの検出結果ではなく、生成時の入力**で比べたいため — 差分に
// 「リポジトリが変わった」ぶんが混ざると、ツール側の変更が埋もれる。
//
// バージョンは入れない。生成物には 1 つずつ印が入っており(#212)、ここに持つと
// 版を上げるたび記録だけが変わって upgrade --check の差分が騒がしくなる。
func (p Params) GenRecord() string {
	b, err := json.MarshalIndent(genRecordDoc{Note: genRecordNote, Params: p.canonical()}, "", "  ")
	if err != nil {
		return ""
	}
	return string(b)
}

// canonical は「実際に生成に使われた値」に揃える。
//
// 空文字と既定値は同じ意味なので(Compute 未指定 = lambda)、そのまま記録すると
// **等価な指定で記録行だけが変わる**。生成物が同じなのに diff が出ることになり、
// upgrade --check が信用できなくなる。
func (p Params) canonical() Params {
	if p.Driver == "" {
		p.Driver = "stack"
	}
	if !p.Static() && p.Compute == "" {
		p.Compute = "lambda"
	}
	// Entrypoint は ALB() の判定がドメインの有無にも依るので、ここでは埋めない
	// (埋めると「ドメインが無いのに alb」という嘘の記録になる)
	return p
}

// ParseGenRecord は生成入力を読む。まず .kagerou/generated.json を見て、
// 無ければ kagerou.yaml のコメント(旧形式)へ落ちる。
//
// dir はリポジトリのルート。記録がどこにも無いなら ok=false。
func ParseGenRecord(dir string, kagerouYaml []byte) (Params, bool) {
	if b, err := os.ReadFile(filepath.Join(dir, GenRecordPath)); err == nil {
		var doc genRecordDoc
		if err := json.Unmarshal(b, &doc); err == nil {
			return doc.Params, true
		}
		// 壊れているなら旧形式へは落ちない。黙って古い記録を使う方が危ない
		return Params{}, false
	}
	return parseGenRecordComment(kagerouYaml)
}

// parseGenRecordComment は旧形式(kagerou.yaml のコメント)を読む。
func parseGenRecordComment(body []byte) (Params, bool) {
	for _, line := range bytes.Split(body, []byte("\n")) {
		s := strings.TrimSpace(string(line))
		if !strings.HasPrefix(s, genRecordPrefix) {
			continue
		}
		var p Params
		if err := json.Unmarshal([]byte(s[len(genRecordPrefix):]), &p); err != nil {
			return Params{}, false
		}
		return p, true
	}
	return Params{}, false
}

// Owner は生成物の持ち主。upgrade --check の出し分けに使う。
type Owner int

const (
	// OwnerKagerou は kagerou が丸ごと生成し直すファイル(workflow / base / kagerou.yaml)。
	// 差分が出たら**取り込むべき変更**なので、そのまま報告する。
	OwnerKagerou Owner = iota
	// OwnerUser は利用者が手を入れる前提のファイル(template.yaml / Dockerfile)。
	// 差分が出るのは正常なので、件数だけ伝えて中身は出さない。
	// ここを他と同じ声で出すと、毎回鳴って誰も読まなくなる。
	OwnerUser
)

// GeneratedFile は「いま生成するとこうなる」1 ファイル。
type GeneratedFile struct {
	Path  string
	Body  []byte
	Owner Owner
}

// Generate は書き出さずに、生成物の中身だけを返す(upgrade --check 用)。
//
// Run と同じ fileSpecs を引くので、片方だけ増えることがない。Dockerfile は
// 含めない — あれは雛形の新規生成か LWA の 1 行注入で、丸ごと比較する対象ではない。
func Generate(p Params, sel Targets) ([]GeneratedFile, error) {
	var out []GeneratedFile
	for _, f := range fileSpecs(p, sel) {
		if !f.enabled {
			continue
		}
		body, err := render(f.tmpl, p)
		if err != nil {
			return nil, err
		}
		owner := OwnerUser
		if f.overwrite {
			owner = OwnerKagerou
		}
		out = append(out, GeneratedFile{Path: f.path, Body: body, Owner: owner})
	}
	return out, nil
}
